# Configuration for the Sash Actuator Service

# GPIO Pins (BCM numbering)
# -------------------------
hall_pins: [5, 6, 13, 19, 26] # Hall effect sensors for position tracking
relay_ext_pin: 27               # Relay pin for extending the actuator (moving UP)
relay_ret_pin: 17               # Relay pin for retracting the actuator (moving DOWN)

# Physical Button Pins
# --------------------
# Assign the BCM pin numbers for your physical up, down, and stop buttons.
# If you don't have a stop button, you can remove the 'stop_pin' line.
buttons:
  up_pin: 23
  down_pin: 24
  stop_pin: 25

# I2C and Current Sensor (INA219)
# -------------------------------
i2c_bus: 1
ina_addr: 0x45
r_shunt: 0.1  # Shunt resistor value in Ohms
i_max: 3.0    # Maximum expected current in Amps

# Movement and Safety Settings
# ----------------------------
# Raw shunt value from the INA219 that indicates a collision.
# These values may need tuning for your specific motor and power supply.
current_threshold_up: 1300
current_threshold_down: -1300

# Timeouts (in seconds)
max_movement_time: 10.0 # Max time allowed for any single movement command
position_timeout: 2.0   # Max time allowed between detecting consecutive hall sensors

# Debounce time for hall sensors in milliseconds
bounce_ms: 10

# File Paths
# ----------
# Path to store the last known position.
position_state_file: "/tmp/position_state"
# Directory for log files.
# For testing: use user-writable directory. For production: use "/var/log/sash_actuator"
log_dir: "/tmp/sash_actuator_logs" 